/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.TransaccionDAO;
import javax.swing.JOptionPane;
import model.Transaccion;


public class FormularioTransacciones extends javax.swing.JDialog {
    private String mode;
    private int numero_recibo;
    private TransaccionDAO dao;
    private ListadoTransacciones parent;
  
    public FormularioTransacciones(ListadoTransacciones pParent, boolean modal, String pMode, int pNumeroRecibo) {
        super(pParent, modal);
        this.parent = pParent;
                        
        initComponents();

        dao = new TransaccionDAO();
        this.mode = pMode;
        this.numero_recibo = pNumeroRecibo;
        txt_id.setText(String.valueOf(pNumeroRecibo));
        txt_id.setEnabled(false);

        if (mode.equals("INS")) {
            setTitle("Formulario Insertar");
            btn_accion.setText("Insertar");
        } else if (mode.equals("UPD")) {
            setTitle("Formulario Actualizar");
            Transaccion t = dao.getById(numero_recibo);
            txt_id_usuario.setText(String.valueOf(t.getIdUsuario()));
            txt_monto.setText(String.valueOf(t.getMonto()));
            txt_descripcion.setText(t.getDescripcion());
            btn_accion.setText("Actualizar");
        } else if (mode.equals("DLT")) {
            setTitle("Formulario Eliminar");
            Transaccion t = dao.getById(numero_recibo);
            txt_id_usuario.setText(String.valueOf(t.getIdUsuario()));
            txt_monto.setText(String.valueOf(t.getMonto()));
            txt_descripcion.setText(t.getDescripcion());

            txt_id_usuario.setEnabled(false);
            txt_monto.setEnabled(false);
            txt_descripcion.setEnabled(false);
            btn_accion.setText("Eliminar");
        }

        lbl_info.setText("100 por día atrasado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        idusuario = new javax.swing.JLabel();
        monto = new javax.swing.JLabel();
        lbl_info = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_id_usuario = new javax.swing.JTextField();
        txt_monto = new javax.swing.JTextField();
        descripcion = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        btn_accion = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        id.setText("ID");

        idusuario.setText("ID Usuario");

        monto.setText("Monto");

        lbl_info.setForeground(new java.awt.Color(255, 0, 51));
        lbl_info.setText("\"100 por dia atrasado\" ");

        txt_id.setEnabled(false);

        txt_id_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_usuarioActionPerformed(evt);
            }
        });

        descripcion.setText("Descripcion");

        btn_accion.setText("jButton1");
        btn_accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accionActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.setPreferredSize(new java.awt.Dimension(113, 35));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(id)
                .addGap(13, 13, 13)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(idusuario)
                .addGap(13, 13, 13)
                .addComponent(txt_id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(monto)
                .addGap(13, 13, 13)
                .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(descripcion)
                .addGap(13, 13, 13)
                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lbl_info))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btn_accion)
                .addGap(11, 11, 11)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(id))
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(idusuario))
                    .addComponent(txt_id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(monto))
                    .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(descripcion))
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lbl_info)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_accion)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accionActionPerformed
        try {
            if (mode.equals("INS")) {
                Transaccion t = new Transaccion();
                t.setIdUsuario(Integer.parseInt(txt_id_usuario.getText()));
                t.setMonto(Double.parseDouble(txt_monto.getText()));
                t.setDescripcion(txt_descripcion.getText());

                dao.insertar(t);
                parent.refrescarInfo();
                this.dispose();
            }

            if (mode.equals("UPD")) {
                Transaccion t = new Transaccion();
                t.setNumeroRecibo(Integer.parseInt(txt_id.getText()));
                t.setIdUsuario(Integer.parseInt(txt_id_usuario.getText()));
                t.setMonto(Double.parseDouble(txt_monto.getText()));
                t.setDescripcion(txt_descripcion.getText());

                dao.actualizar(t);
                parent.refrescarInfo();
                this.dispose();
            }

            if (mode.equals("DLT")) {
                dao.eliminar(numero_recibo);
                parent.refrescarInfo();
                this.dispose();
            }                                                                                           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btn_accionActionPerformed

    private void txt_id_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_usuarioActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

  
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accion;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idusuario;
    private javax.swing.JLabel lbl_info;
    private javax.swing.JLabel monto;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id_usuario;
    private javax.swing.JTextField txt_monto;
    // End of variables declaration//GEN-END:variables
}
